<a href="https://colab.research.google.com/github/maher-nakesh/Data_mining_course/blob/main/DataSet_domy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
Dataset = pd.read_csv("/content/drive/MyDrive/Dataset.csv")
x= Dataset.iloc[:,:-1].values
y=Dataset.iloc[:,-1].values

In [14]:
print(x)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [15]:
print (y)

0    No 
1    Yes
2    No 
3    No 
4    Yes
5    Yes
6    No 
7    Yes
8    No 
9    Yes
Name: Purchased, dtype: object


In [20]:
from sklearn.impute import SimpleImputer
imputa=SimpleImputer(missing_values=np.nan,strategy='mean')
imputa.fit(x[:,1:3])
x[:,1:3]=imputa.transform(x[:,1:3])

In [21]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [24]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [26]:
print(y) 

[0 1 0 0 1 1 0 1 0 1]


In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2)

In [28]:
print(x_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 1.0 38.0 61000.0]]


In [29]:
print(x_test)

[[0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [30]:
print(y_test)

[1 0]


In [31]:
print(y_train)

[1 1 1 0 1 0 0 0]


In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.fit_transform(x_test[:,3:])

In [33]:
print(x_train)

[[0.0 1.0 0.0 0.22561095973072184 0.05040823668012247]
 [1.0 0.0 0.0 1.7912966561752484 1.8325833141450703]
 [1.0 0.0 0.0 -0.7529426005471072 -0.6260377781240918]
 [0.0 1.0 0.0 -1.7314961608249362 -1.0943465576039322]
 [1.0 0.0 0.0 -0.3615211764359756 0.42765697570554906]
 [1.0 0.0 0.0 1.008453807952985 1.0130429500553495]
 [0.0 0.0 1.0 -0.013591021670525094 -1.3285009473438525]
 [0.0 0.0 1.0 -0.16581046438040975 -0.27480619351421154]]


In [34]:
print(x_test)

[[0.0 0.0 1.0 -1.0 -1.0]
 [0.0 1.0 0.0 1.0 1.0]]
